Add missing import of exit
Resolve:

```
In [1]: from version import get_version

In [2]: get_version()
fatal: No names found, cannot describe anything.
Unable to get version number from git tags
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-2-77116a08a28f> in <module>()
----> 1 get_version()

/home/blyenth/dev/company-time-clock/version.py in get_version()
     26         except CalledProcessError:
     27             print('Unable to get version number from git tags')
---> 28             exit(1)
     29 
     30         # PEP 440 compatibility

NameError: global name 'exit' is not defined
```